# Generated by Django 5.2.1 on 2025-06-29 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='has_position_related_high_education',
        ),
        migrations.AlterField(
            model_name='employee',
            name='application_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicationlink'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='distance_to_work',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='had_leadership_role',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='percentage_of_matching_skills',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='predicted_avg_absence_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='predicted_avg_attendance_lateness_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='predicted_avg_task_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='predicted_avg_time_remaining_before_deadline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
