# Generated by Django 5.2.1 on 2025-06-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='profile_image',
            field=models.ImageField(default=0, upload_to='profile_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_education_degree',
            field=models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_education_field',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('medicine', 'Medicine'), ('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce'), ('law', 'Law'), ('education', 'Education')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(choices=[('cairo', 'Cairo'), ('giza', 'Giza'), ('alexandria', 'Alexandria'), ('delta', 'Delta'), ('upper_egypt', 'Upper Egypt'), ('canal_cities', 'Canal Cities'), ('border', 'Border Governorates')], max_length=100),
        ),
    ]
