# Generated by Django 5.2.1 on 2025-06-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_basicinfo_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cv_image',
            field=models.ImageField(default='cvs/default.jpg', upload_to='cvs/'),
        ),
    ]
