# Generated by Django 5.2.1 on 2025-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_has_position_related_high_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AddField(
            model_name='employee',
            name='has_position_related_high_education',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
