# Generated by Django 5.2.1 on 2025-06-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_employee_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, to='api.skill'),
        ),
    ]
