# Generated by Django 5.2.1 on 2025-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_basicinfo_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
