# Generated by Django 5.2.1 on 2025-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_basicinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
