# Generated by Django 5.2.1 on 2025-06-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='distance_to_work',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
