# Generated by Django 5.2.1 on 2025-06-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_region_distance_to_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='distance_to_work',
        ),
    ]
