# Generated by Django 5.2.1 on 2025-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_employee_distance_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avg_absence_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avg_attendance_lateness_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avg_task_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avg_time_remaining_before_deadline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_absence_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_lateness_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_task_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_time_remaining',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
