# Generated by Django 5.2.1 on 2025-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_file_file_alter_position_name_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv_image',
        ),
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(default='cvs/default.pdf', upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='holioronlinedayweekday',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='holioronlinedayyearday',
            constraint=models.UniqueConstraint(fields=('month', 'day'), name='unique_month_day'),
        ),
    ]
