# Generated by Django 5.2.1 on 2025-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_publicholiday_workdayconfig_attendancerecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='late_days',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='overtime_hours',
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of all salary factors for this month.'),
        ),
    ]
