# Generated by Django 5.2.1 on 2025-07-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employee_avg_absence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='scheduling_interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_employees', to='api.hr'),
        ),
    ]
