# Generated by Django 5.2.3 on 2025-06-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_employee_cv_image_employee_cv_and_more'),
    ]

    operations = [
    ]
