# Generated by Django 5.2.1 on 2025-07-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_employee_scheduling_interviewer'),
        ('api', '0008_remove_salaryrecord_absent_days_and_more'),
    ]

    operations = [
    ]
