# Generated by Django 5.2.1 on 2025-07-07 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250707_1207'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimerequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_overtime_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_absence_days',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_lateness_hrs',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_task_rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_time_remaining',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='attendance_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_request', to='api.attendancerecord'),
        ),
        migrations.DeleteModel(
            name='OvertimeClaim',
        ),
    ]
