# Generated by Django 5.2.1 on 2025-07-05 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250705_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_absence_days',
            field=models.FloatField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_lateness_hrs',
            field=models.FloatField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_task_rating',
            field=models.FloatField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_time_remaining',
            field=models.FloatField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
