# Generated by Django 5.2.1 on 2025-07-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_hr_accepted_employees_avg_absence_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_absence_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_lateness_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_task_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_time_remaining',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
