# Generated by Django 5.2.3 on 2025-07-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_overtimerequest_options_and_more'),
        ('api', '0011_alter_hr_accepted_employees_avg_absence_days_and_more'),
    ]

    operations = [
    ]
