# Generated by Django 5.2.3 on 2025-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20250711_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineDayWeekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Weekly Online Day',
                'verbose_name_plural': 'Weekly Online Days',
            },
        ),
        migrations.CreateModel(
            name='OnlineDayYearday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Yearly Online Day',
                'verbose_name_plural': 'Yearly Online Days',
            },
        ),
        migrations.RenameModel(
            old_name='HoliOrOnlineDayWeekday',
            new_name='HolidayWeekday',
        ),
        migrations.RenameModel(
            old_name='HoliOrOnlineDayYearday',
            new_name='HolidayYearday',
        ),
        migrations.AlterModelOptions(
            name='holidayweekday',
            options={'verbose_name': 'Weekly Holiday', 'verbose_name_plural': 'Weekly Holidays'},
        ),
        migrations.AlterModelOptions(
            name='holidayyearday',
            options={'verbose_name': 'Yearly Holiday', 'verbose_name_plural': 'Yearly Holidays'},
        ),
        migrations.RemoveConstraint(
            model_name='holidayyearday',
            name='unique_month_day',
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_absence_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_lateness_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_task_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='accepted_employees_avg_time_remaining',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='holidayyearday',
            constraint=models.UniqueConstraint(fields=('month', 'day'), name='unique_holiday_month_day'),
        ),
        migrations.AddField(
            model_name='onlinedayweekday',
            name='employees',
            field=models.ManyToManyField(to='api.employee'),
        ),
        migrations.AddField(
            model_name='onlinedayyearday',
            name='employees',
            field=models.ManyToManyField(to='api.employee'),
        ),
        migrations.AddConstraint(
            model_name='onlinedayyearday',
            constraint=models.UniqueConstraint(fields=('month', 'day'), name='unique_online_month_day'),
        ),
    ]
