# Generated by Django 5.2.3 on 2025-07-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_onlinedayweekday_onlinedayyearday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicHoliday',
        ),
        migrations.DeleteModel(
            name='WorkDayConfig',
        ),
    ]
