# Generated by Django 5.2.3 on 2025-07-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_publicholiday_delete_workdayconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
