# Generated by Django 5.2.3 on 2025-07-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='lateness_hours',
            field=models.FloatField(default=0),
        ),
    ]
