# Generated by Django 5.2.3 on 2025-07-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_attendancerecord_lateness_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='number_of_absent_days',
            new_name='total_absent_days',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lateness_hours',
            new_name='total_lateness_hours',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='overtime_hours',
            new_name='total_overtime_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='avg_absence_days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='avg_attendance_lateness_hrs',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='avg_task_rating',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='avg_time_remaining_before_deadline',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_attend_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_leave_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='short_time_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='number_of_accepted_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_of_non_holiday_days_since_join',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_task_ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_time_remaining_before_deadline',
            field=models.FloatField(default=0),
        ),
    ]
