# Generated by Django 5.2.3 on 2025-07-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_number_of_absent_days_employee_total_absent_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='predicted_avg_absence_days',
            new_name='predicted_avg_absent_days',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='predicted_avg_attendance_lateness_hrs',
            new_name='predicted_avg_lateness_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_prediction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='predicted_avg_overtime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='predicted_basic_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
