# Generated by Django 5.2.3 on 2025-07-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_predicted_avg_absence_days_employee_predicted_avg_absent_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('total_employees', models.IntegerField()),
                ('total_hrs', models.IntegerField()),
                ('position_stats', models.JSONField(default=dict)),
                ('monthly_salary_totals', models.JSONField(default=list)),
                ('overall_avg_task_rating', models.FloatField(null=True)),
                ('overall_avg_time_remaining', models.FloatField(null=True)),
                ('overall_avg_overtime', models.FloatField(null=True)),
                ('overall_avg_lateness', models.FloatField(null=True)),
                ('overall_avg_absent_days', models.FloatField(null=True)),
                ('overall_avg_salary', models.FloatField(null=True)),
            ],
        ),
    ]
