# Generated by Django 5.2.3 on 2025-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_hr_accepted_employees_avg_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='accepted_employees_avg_interviewer_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
