# Generated by Django 5.2.3 on 2025-07-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_hr_accepted_employees_avg_interviewer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='interviewer_rating_to_absence_days_correlation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='interviewer_rating_to_avg_overtime_correlation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='interviewer_rating_to_lateness_hrs_correlation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='interviewer_rating_to_task_rating_correlation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='interviewer_rating_to_time_remaining_correlation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
