# Generated by Django 5.2.3 on 2025-07-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_hr_interviewer_rating_to_absence_days_correlation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='last_stats_calculation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
