# Generated by Django 5.2.3 on 2025-07-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_hr_last_stats_calculation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
