# Generated by Django 5.2.3 on 2025-07-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_casualleave_employeeleavepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_latitude',
            field=models.FloatField(blank=True, help_text="Employee's latitude during check-in", null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_longitude',
            field=models.FloatField(blank=True, help_text="Employee's longitude during check-in", null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_latitude',
            field=models.FloatField(blank=True, help_text="Employee's latitude during check-out", null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_longitude',
            field=models.FloatField(blank=True, help_text="Employee's longitude during check-out", null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='allowed_radius_meters',
            field=models.IntegerField(default=100, help_text='Allowed radius in meters for attendance check-in'),
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Building latitude for attendance validation', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Building longitude for attendance validation', null=True),
        ),
    ]
