# Generated by Django 5.2.3 on 2025-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_attendancerecord_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.CharField(default='https://example.com/placeholder.pdf', max_length=1000),
            preserve_default=False,
        ),
    ]
