# Generated by Django 5.2.3 on 2025-07-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_file_file_file_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
