# Generated by Django 5.2.3 on 2025-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_basicinfo_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
        migrations.AddField(
            model_name='employee',
            name='cv_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
