# Generated by Django 5.2.3 on 2025-07-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_casualleave_performance_indexes'),
        ('api', '0029_remove_employee_cv_employee_cv_url'),
    ]

    operations = [
    ]
