# Generated by Django 5.2.3 on 2025-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20250722_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualleave',
            name='duration',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
