# Generated by Django 5.2.3 on 2025-07-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_casualleave_enhanced_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatistics',
            name='region_stats',
            field=models.JSONField(default=dict),
        ),
    ]
