# Generated by Django 5.2.3 on 2025-07-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_companystatistics_region_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cairo Headquarters', max_length=100)),
                ('latitude', models.FloatField(default=30.05)),
                ('longitude', models.FloatField(default=31.2333)),
                ('allowed_radius_meters', models.IntegerField(default=150)),
            ],
        ),
    ]
