# Generated by Django 5.2.3 on 2025-07-23 09:07

from django.db import migrations


def create_default_headquarters(apps, schema_editor):
    """Create the default headquarters instance."""
    Headquarters = apps.get_model("api", "Headquarters")

    # Only create if no headquarters exists
    if not Headquarters.objects.exists():
        Headquarters.objects.create(
            name="Cairo Headquarters",
            latitude=30.0500,
            longitude=31.2333,
            allowed_radius_meters=150,
        )


def remove_headquarters(apps, schema_editor):
    """Remove the headquarters instance (reverse migration)."""
    Headquarters = apps.get_model("api", "Headquarters")
    Headquarters.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_add_headquarters"),
    ]

    operations = [
        migrations.RunPython(create_default_headquarters, remove_headquarters),
    ]
