# Generated by Django 5.2.3 on 2025-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_populate_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
