# Generated by Django 5.2.3 on 2025-07-24 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_employee_position_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='is_deleted',
        ),
    ]
