# Generated by Django 5.2.3 on 2025-07-25 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_employee_is_deleted_remove_hr_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', 'date'], name='api_attenda_user_id_1bee7e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='api_attenda_date_aed991_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['overtime_approved', 'overtime_hours'], name='api_attenda_overtim_583f88_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['-date'], name='api_attenda_date_c6de11_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['status', 'reviewed_at'], name='api_overtim_status_11284e_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['status', '-requested_at'], name='api_overtim_status_dc8c21_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['-reviewed_at'], name='api_overtim_reviewe_673565_idx'),
        ),
    ]
